name: seven_days_web
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  firebase_storage: ^10.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_riverpod: ^1.0.4
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  pageviewj: ^0.0.3
  provider: ^6.0.3
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
